import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  
    background: {
      flex: 1,
      alignItems: 'center',
      alignContent: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(150, 85, 227, 1)',
    },
    home_ribbon: {
      position: 'absolute',
      top: 0,
    },
    //drnklog title
    title_text: {
      flex: 1,
      color: 'rgb(238, 151, 151)',
      fontSize: 64,
      fontWeight: 800,
      fontFamily: 'Sans',
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      textAlign: 'center',
      textAlignVertical: 'top',
    },
    //landing page buttons
    login_button: {
      borderRadius: 60,
      backgroundColor: 'rgb(133, 205, 186)',
      margin: 10,
      height: 90,
      width: 300,
      alignContent: 'center',
      textAlign: 'center',
      justifyContent: 'center',
      color: 'rgb(0, 0, 0)',
      fontFamily: 'Sans-serif',
      fontSize: 28,
      fontWeight: 800,
      shadowColor: 'rgb(0,0,0)',
      shadowRadius: 4,
      textAlignVertical: 'center',
    },
    signup_button: {
      borderRadius: 60,
      backgroundColor: 'rgb(64, 175, 120)',
      margin: 10,
      height: 90,
      width: 300,
      alignContent: 'center',
      textAlign: 'center',
      color: 'rgb(0, 0, 0)',
      fontFamily: 'Sans-serif',
      fontSize: 28,
      fontWeight: 800,
      shadowColor: 'rgb(0,0,0)',
      shadowRadius: 4,
      textAlignVertical: 'center',  
    },
    button_text: {
      alignSelf: 'center',
      textAlign: 'center',
      justifyContent: 'center',
      alignContent: 'center',
      color: 'rgb(0, 0, 0)',
      fontFamily: 'Sans',
      fontSize: 28,
      fontWeight: 800,
    },
    backButton: {
      borderRadius: 60,
      backgroundColor: 'rgb(160, 160, 160)',
      margin: 10,
      height: 90,
      width: 300,
      marginBottom: 10,
      alignContent: 'center',
      textAlign: 'center',
      justifyContent: 'center',
      color: 'rgb(0, 0, 0)',
      fontFamily: 'Sans-serif',
      fontSize: 28,
      fontWeight: 800,
      shadowColor: 'rgb(0,0,0)',
      shadowRadius: 4,
      textAlignVertical: 'center',
    },
    //home page
    homeContainer: {
      flex: 3,
      justifyContent: 'center',
      alignContent: 'center',
      alignItems: 'center',
      padding: 12,      
    },
    home: {
      alignItems: 'center',
      justifyContent: 'center',
      alignContent: 'center',
      width: 300,
      height: 120,
      borderRadius: 10,
      shadowRadius: 4,
      flexDirection: 'row',
    },

    homeText: {
      fontFamily: 'Sans', 
      fontSize: 48,
      fontWeight: 800,
      color: 'rgb(59, 13, 110)',
    },
    //login, sign up page
    input: {
      color: 'rgba(0, 0, 0, .6)',
      fontSize: 24,
      fontFamily: 'Sans',
      padding: 10,
      margin: 10,
      width: 300,
      height: 80,
      borderRadius: 10,
      backgroundColor: 'rgba(255, 255, 255, 0.6)',
    },
    loginForm: {
      alignContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
      justifyContent: 'center',
      textAlign: 'center',
      position: 'absolute',
      bottom: 20,
    },
    entries: {
      fontSize: 64,
      margin: 20,
      letterSpacing: 18,
      height: 100,
      width: 300,
      backgroundColor: 'rgb(114, 137, 238)',
    },
    //for addEntryForm and editEntryForm
    inputContainer: {
      padding: 16,
    },
    entryFields: {
      height: 60,
      width: 300,
      borderColor: 'gray',
      borderWidth: 1,
      marginBottom: 12,
      paddingHorizontal: 8,
      backgroundColor: 'rgb(214, 214, 214)',
      fontFamily: 'Sans',
      fontSize: 24,
      shadowRadius: 4,
      color: 'rgb(0, 0, 0)',
      fontWeight: 600,
    },
    //floating add entry button on myLog page
    addButton: {
      backgroundColor: 'rgb(238, 151, 151)',
      height: 80,
      width: 80,
      position: 'absolute',
      bottom: 20,
      right: 20,
      borderRadius: 50,
      overflow: 'hidden', 
      fontSize: 24,
      fontWeight: 800,
      textAlign: 'center',
      textAlignVertical: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      alignContent: 'center',
    },
    //display item on myLog
    item: {
      paddingLeft: 4,
      paddingRight: 4,
      marginVertical: 8,
      marginLeft: 4,
      height: 80,
      width: 330,
      borderRadius: 5,
      backgroundColor: 'rgb(230, 230, 230)',
      textAlign: 'center',
      textAlignVertical: 'center',
      justifyContent: 'center',
      alignContent: 'center',
      alignSelf: 'center',
      fontSize: 28,
      fontFamily: 'Sans',
    },
    //might not need this
    itemContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#6e3b6e',
    },
    swipeDeleteButton: {
      backgroundColor: 'red',
      justifyContent: 'center',
      alignItems: 'center',
      width: 120,
      height: 80,
      marginVertical: 8,
      marginRight: 16,
      
    },
    swipeDeleteButtonText: {
      color: 'white',
      fontWeight: 600,
      fontSize: 28,
    },

    //viewEntryForm styles
    viewContainer: {
      padding: 10,
      width: 360,
      borderRadius: 4,
      backgroundColor: 'rgba(255, 255, 255, 0.8)',
    },
    viewFields: {
      fontFamily: 'Sans',
      fontSize: 20,
      color: 'rgb(140, 140, 140)',
    },
    viewValues: {
      fontFamily: 'Sans',
      fontSize: 24,
      color: 'rgb(0, 0, 0)',
      fontWeight: 600,
    },
    viewEntryButtonContainer: {
      flexDirection: 'row',
    },
    editButton: {
      borderRadius: 60,
      backgroundColor: 'rgb(210, 130, 0)',
      margin: 10,
      height: 50,
      width: 160,
      alignContent: 'center',
      textAlign: 'center',
      justifyContent: 'center',
      color: 'rgb(0, 0, 0)',
      fontFamily: 'Sans-serif',
      fontSize: 20,
      fontWeight: 600,
      shadowColor: 'rgb(0,0,0)',
      shadowRadius: 4,
      textAlignVertical: 'center',
    },
    deleteButton: {
      borderRadius: 60,
      backgroundColor: 'rgb(255, 0, 0)',
      margin: 10,
      height: 50,
      width: 160,
      shadowColor: 'rgb(0,0,0)',
      shadowRadius: 4,
      alignContent: 'center',
      alignItems: 'center',
      textAlignVertical: 'center',
      textAlign: 'center',
      justifyContent: 'center',
    },
    deleteButtonText: {
      fontSize: 20,
      fontWeight: 600,
      alignContent: 'center',
      textAlign: 'center',
      justifyContent: 'center',
      color: 'rgb(0, 0, 0)',
      fontFamily: 'Sans-serif',
      textAlignVertical: 'center',
      alignItems: 'center',
      alignSelf: 'center', 
    },
    //navigator bar
    navigatorBarContainer: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      padding: 16,
      backgroundColor: '#f0f0f0', 
    },
    navigatorBarButton: {
      padding: 8,
    },
});
